#!/bin/bash

# Convenience script for building Enry Server

echo "Building Enry server"

hash glide >/dev/null 2>&1 || { echo "Please install Glide https://github.com/Masterminds/glide#install" >&2; exit 1; }
glide install

make build
if [[ "$?" -ne 0 ]]; then
  echo "To build a Golang project ${PWD}, please check that its is under GOPATH=$GOPATH"
  exit 1
fi
echo "Done"
