#!/bin/bash -e

cd "$(dirname $(readlink -f $0))"

echo "Building Enry server"

hash glide >/dev/null 2>&1 || { echo "Please install Glide https://github.com/Masterminds/glide#install" >&2; exit 1; }

if ! make build ; then
  echo "To build a Golang project ${PWD}, please check that its is under GOPATH=$GOPATH"
  exit 1
fi
echo "Done"
