#!/bin/bash

# Convenience script to run Berserker using Apache Spark local mode

hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }
hash siva >/dev/null 2>&1 || { echo "Please go-siva https://github.com/src-d/go-siva#installation" >&2; exit 1; }

# the only way to work around idiosyncratic "sbt run" args
command="./sbt \"run $@\""
sh -c "exec $command"
