#!/bin/bash

# Convenience script to run Berserker on Apache Spark cluster
# Asssume you have Apache Spark installed and configured locally

E_NOT_BUILT=140
E_NO_SPARK=141

siva="$GOPATH/bin/siva"
siva_build_command="go get -u gopkg.in/src-d/go-siva.v1/..."
jar="target/scala-2.11/berserker-0.0.2.sjar"
build_command="./sbt package"


hash java >/dev/null 2>&1 || { echo "Please install Java" >&2; exit 1; }

if [[ ! -f "${jar}" ]]; then
    echo "${jar} not found. Running build ${build_command}"
    $build_command
fi

if [[ ! -f "${siva}" ]]; then
    echo "go-siva binary not found in ${siva}. Installing it using ${siva_build_command}"
    hash go >/dev/null 2>&1 || { echo "Please install Golang" >&2; exit 1; }
    $siva_build_command
fi



sparkSubmit() {
    if hash spark-submit 2>/dev/null; then
        spark-submit "$@"
    elif [[ -n "${SPARK_HOME}" ]]; then
        echo "Using spark-submit from ${SPARK_HOME}"
        "${SPARK_HOME}/bin/spark-submit" "$@"
    else
        echo "Please, install and configure Apache Spark and set SPARK_HOME"
        exit "${E_NO_SPARK}"
    fi
}


sparkSubmit \
  --class tech.sourced.berserker.SparkDriver \
  --master "${MASTER:=yarn}" \
  --name "Berserker (UAST extractor)" \
  --files "$GOPATH/bin/siva,./siva-unpack-mock" \
  "${PWD}/${jar}" \
  "$@"
