#!/bin/bash

# Convenience script for building Berserker

echo "Building dependency: Enry server"
cd enrysrv
if ! ./build ; then
    exit 2
fi
cd ..


echo "Building Berserker"
hash java >/dev/null 2>&1 || { echo "Please install JVM" >&2; exit 1; }
./sbt package
